id: b8e3bae962fb4933aadd2a66257ffa47
initial_creation_type: ocr
source_metadata:
  volumes:
    0ba75ade96124d5b8a9585a557805e7d:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སེམས་ཅན་མགུ་བར་བྱ་བའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
