id: D120865ED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:58:46+00:00'
last_modified: '2022-05-26T06:05:58.891163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a733:
      image_group_id: I1PD95846
      title: སེམས་ཅན་མགུ་བར་བྱ་བའི་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: a733.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
